title: Computing
description: Knowledge base for students of computing
theme: just-the-docs

url: https://https://swavekwlodkowski.github.io/computing/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
